import { getAllIngredients, saveIngredient, deleteIngredient } from './ingredients'
import { newId, now } from '@/utils/ids'
import type { Ingredient, IngredientUnit } from '@/types'

interface VDef {
  brand: string
  sz: number; su: string; du: string
  cal: number; pro: number; carb: number
  fib: number; sug: number; fat: number; sod: number
  sf?: number; fdc?: number
}

interface IDef {
  name: string
  cat: string
  peri?: boolean
  variants: VDef[]
}

// Names of old flat-seeded entries (single Generic variant) to remove during migration
export const LEGACY_FLAT_NAMES = [
  'Chicken Breast (Raw)', 'Chicken Thigh (Raw)', 'Chicken Drumstick (Raw)',
  'Ground Beef (80/20)', 'Ground Turkey', 'Pork Tenderloin', 'Bacon',
  'Salmon (Atlantic)', 'Shrimp', 'Tuna (Canned in Water)',
  'Eggs (Large)', 'Milk (Whole)', 'Milk (2%)', 'Milk (Skim)',
  'Greek Yogurt (Plain)', 'Butter (Unsalted)', 'Cottage Cheese',
  'Bell Pepper (Red)', 'White Rice (Dry)', 'Brown Rice (Dry)',
  'Pasta (Dry)', 'Quinoa (Dry)', 'Olive Oil',
  'Almonds (Raw)', 'Walnuts (Raw)',
  'Black Beans (Canned)', 'Chickpeas (Canned)', 'Lentils (Cooked)',
  'Brown Sugar',
]

// prettier-ignore
const DEFS: IDef[] = [
  // ─── Meat ─────────────────────────────────────────────────────────────────
  { name:'Ground Beef', cat:'Meat & Poultry', peri:true, variants:[
    { brand:'80/20 Raw',  sz:100, su:'g', du:'oz', cal:254, pro:17.2, carb:0, fib:0, sug:0, fat:20.0, sod:72,  sf:7.9, fdc:174036 },
    { brand:'85/15 Raw',  sz:100, su:'g', du:'oz', cal:215, pro:19.0, carb:0, fib:0, sug:0, fat:15.0, sod:72,  sf:5.9 },
    { brand:'90/10 Raw',  sz:100, su:'g', du:'oz', cal:176, pro:20.1, carb:0, fib:0, sug:0, fat:10.0, sod:72,  sf:3.9 },
    { brand:'93/7 Raw',   sz:100, su:'g', du:'oz', cal:152, pro:21.4, carb:0, fib:0, sug:0, fat:7.0,  sod:72,  sf:2.8 },
  ]},
  { name:'Chicken Breast', cat:'Meat & Poultry', peri:true, variants:[
    { brand:'Boneless Skinless Raw', sz:100, su:'g', du:'oz', cal:120, pro:22.5, carb:0, fib:0, sug:0, fat:2.6, sod:74, sf:0.7, fdc:171477 },
    { brand:'Bone-In Skin-On Raw',   sz:100, su:'g', du:'oz', cal:172, pro:20.6, carb:0, fib:0, sug:0, fat:9.7, sod:76, sf:2.7 },
  ]},
  { name:'Chicken Thigh', cat:'Meat & Poultry', peri:true, variants:[
    { brand:'Boneless Skinless Raw', sz:100, su:'g', du:'oz', cal:177, pro:17.9, carb:0, fib:0, sug:0, fat:11.6, sod:89, sf:3.2, fdc:171479 },
  ]},
  { name:'Chicken Drumstick', cat:'Meat & Poultry', peri:true, variants:[
    { brand:'Raw', sz:100, su:'g', du:'oz', cal:172, pro:19.5, carb:0, fib:0, sug:0, fat:10.2, sod:87 },
  ]},
  { name:'Ground Turkey', cat:'Meat & Poultry', peri:true, variants:[
    { brand:'93/7 Raw', sz:100, su:'g', du:'oz', cal:149, pro:19.7, carb:0, fib:0, sug:0, fat:7.6, sod:77, fdc:171506 },
  ]},
  { name:'Beef Sirloin Steak', cat:'Meat & Poultry', peri:true, variants:[
    { brand:'Generic', sz:100, su:'g', du:'oz', cal:207, pro:26.1, carb:0, fib:0, sug:0, fat:10.6, sod:75, sf:4.5 },
  ]},
  { name:'Pork Chop', cat:'Meat & Poultry', peri:true, variants:[
    { brand:'Boneless Raw', sz:100, su:'g', du:'oz', cal:143, pro:21.0, carb:0, fib:0, sug:0, fat:5.9, sod:53, sf:2.0, fdc:168323 },
    { brand:'Bone-In Raw',  sz:100, su:'g', du:'oz', cal:172, pro:20.5, carb:0, fib:0, sug:0, fat:9.6, sod:56, sf:3.4 },
  ]},
  { name:'Bacon', cat:'Meat & Poultry', peri:true, variants:[
    { brand:'Raw Pork', sz:100, su:'g', du:'oz', cal:458, pro:12.6, carb:1.3, fib:0, sug:0, fat:45.0, sod:662, fdc:168293 },
  ]},
  // ─── Seafood ───────────────────────────────────────────────────────────────
  { name:'Salmon', cat:'Seafood', peri:true, variants:[
    { brand:'Atlantic Raw', sz:100, su:'g', du:'oz', cal:208, pro:20.4, carb:0, fib:0, sug:0, fat:13.4, sod:59, sf:3.1, fdc:175167 },
  ]},
  { name:'Tilapia', cat:'Seafood', peri:true, variants:[
    { brand:'Generic', sz:100, su:'g', du:'oz', cal:96, pro:20.1, carb:0, fib:0, sug:0, fat:1.7, sod:56, fdc:175177 },
  ]},
  { name:'Shrimp', cat:'Seafood', peri:true, variants:[
    { brand:'Raw Peeled', sz:100, su:'g', du:'oz', cal:85, pro:20.1, carb:0.9, fib:0, sug:0, fat:0.9, sod:119, fdc:175176 },
  ]},
  { name:'Tuna', cat:'Seafood', variants:[
    { brand:'Canned in Water', sz:100, su:'g', du:'oz', cal:116, pro:26.0, carb:0, fib:0, sug:0, fat:1.0, sod:339 },
  ]},
  { name:'Cod', cat:'Seafood', peri:true, variants:[
    { brand:'Generic', sz:100, su:'g', du:'oz', cal:82, pro:17.8, carb:0, fib:0, sug:0, fat:0.7, sod:78 },
  ]},
  // ─── Eggs ──────────────────────────────────────────────────────────────────
  { name:'Eggs', cat:'Eggs', peri:true, variants:[
    { brand:'Large Whole',      sz:1, su:'each', du:'each', cal:72, pro:6.3, carb:0.4, fib:0, sug:0.2, fat:5.0, sod:71, fdc:748967 },
    { brand:'Large White Only', sz:1, su:'each', du:'each', cal:17, pro:3.6, carb:0.2, fib:0, sug:0.2, fat:0.1, sod:55 },
    { brand:'Large Yolk Only',  sz:1, su:'each', du:'each', cal:55, pro:2.7, carb:0.6, fib:0, sug:0.1, fat:4.5, sod:8 },
  ]},
  { name:'Liquid Egg Whites', cat:'Eggs', peri:true, variants:[
    { brand:'Generic', sz:100, su:'g', du:'oz', cal:52, pro:10.9, carb:0.7, fib:0, sug:0.7, fat:0.2, sod:170 },
  ]},
  // ─── Dairy ─────────────────────────────────────────────────────────────────
  { name:'Milk', cat:'Dairy', peri:true, variants:[
    { brand:'Whole',     sz:240, su:'ml', du:'cup', cal:146, pro:7.7, carb:11.4, fib:0, sug:12.3, fat:7.9, sod:103, sf:4.6 },
    { brand:'2 Percent', sz:240, su:'ml', du:'cup', cal:120, pro:8.1, carb:11.5, fib:0, sug:12.2, fat:4.9, sod:107, sf:2.9 },
    { brand:'Skim',      sz:240, su:'ml', du:'cup', cal:83,  pro:8.3, carb:12.3, fib:0, sug:12.3, fat:0.2, sod:103 },
  ]},
  { name:'Greek Yogurt', cat:'Dairy', peri:true, variants:[
    { brand:'Plain Nonfat', sz:170, su:'g', du:'oz', cal:100, pro:17.3, carb:6.1, fib:0, sug:6.1, fat:0.7, sod:61, fdc:170903 },
  ]},
  { name:'Cheddar Cheese', cat:'Dairy', peri:true, variants:[
    { brand:'Generic', sz:28, su:'g', du:'oz', cal:113, pro:7.0, carb:0.4, fib:0, sug:0.1, fat:9.3, sod:174, sf:5.9, fdc:173414 },
  ]},
  { name:'Mozzarella', cat:'Dairy', peri:true, variants:[
    { brand:'Generic', sz:28, su:'g', du:'oz', cal:72, pro:7.1, carb:0.8, fib:0, sug:0.3, fat:4.5, sod:175, fdc:173420 },
  ]},
  { name:'Parmesan Cheese', cat:'Dairy', peri:true, variants:[
    { brand:'Generic', sz:5, su:'g', du:'g', cal:22, pro:1.9, carb:0.2, fib:0, sug:0, fat:1.4, sod:76 },
  ]},
  { name:'Butter', cat:'Dairy', peri:true, variants:[
    { brand:'Unsalted', sz:14, su:'g', du:'tbsp', cal:101, pro:0.1, carb:0, fib:0, sug:0, fat:11.5, sod:2, sf:7.3, fdc:173430 },
  ]},
  { name:'Cream Cheese', cat:'Dairy', peri:true, variants:[
    { brand:'Generic', sz:30, su:'g', du:'oz', cal:99, pro:1.7, carb:1.2, fib:0, sug:1.0, fat:9.8, sod:92, fdc:173417 },
  ]},
  { name:'Cottage Cheese', cat:'Dairy', peri:true, variants:[
    { brand:'Low-Fat 2%', sz:113, su:'g', du:'oz', cal:81, pro:14.0, carb:3.1, fib:0, sug:3.1, fat:1.1, sod:459, fdc:173418 },
  ]},
  { name:'Heavy Cream', cat:'Dairy', peri:true, variants:[
    { brand:'Generic', sz:15, su:'ml', du:'tbsp', cal:51, pro:0.4, carb:0.4, fib:0, sug:0.4, fat:5.4, sod:4, sf:3.4, fdc:170859 },
  ]},
  { name:'Sour Cream', cat:'Dairy', peri:true, variants:[
    { brand:'Generic', sz:30, su:'g', du:'tbsp', cal:57, pro:0.7, carb:1.4, fib:0, sug:1.4, fat:5.5, sod:15 },
  ]},
  // ─── Produce – Vegetables ──────────────────────────────────────────────────
  { name:'Broccoli',        cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:34,  pro:2.8, carb:6.6,  fib:2.6, sug:1.7,  fat:0.4, sod:33,  fdc:170379 }]},
  { name:'Spinach',         cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:23,  pro:2.9, carb:3.6,  fib:2.2, sug:0.4,  fat:0.4, sod:79,  fdc:168462 }]},
  { name:'Kale',            cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:49,  pro:4.3, carb:8.8,  fib:3.6, sug:2.3,  fat:0.9, sod:38,  fdc:168421 }]},
  { name:'Carrots',         cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:41,  pro:0.9, carb:9.6,  fib:2.8, sug:4.7,  fat:0.2, sod:69,  fdc:170393 }]},
  { name:'Sweet Potato',    cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:86,  pro:1.6, carb:20.1, fib:3.0, sug:4.2,  fat:0.1, sod:55,  fdc:168482 }]},
  { name:'Russet Potato',   cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:79,  pro:2.1, carb:18.1, fib:1.3, sug:0.8,  fat:0.1, sod:6,   fdc:170027 }]},
  { name:'Yellow Onion',    cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:40,  pro:1.1, carb:9.3,  fib:1.7, sug:4.2,  fat:0.1, sod:4,   fdc:170000 }]},
  { name:'Garlic',          cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'g',  cal:149, pro:6.4, carb:33.1, fib:2.1, sug:1.0,  fat:0.5, sod:17,  fdc:169230 }]},
  { name:'Tomato',          cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:18,  pro:0.9, carb:3.9,  fib:1.2, sug:2.6,  fat:0.2, sod:5,   fdc:170457 }]},
  { name:'Bell Pepper',     cat:'Produce', peri:true, variants:[{ brand:'Red Raw',  sz:100, su:'g', du:'oz', cal:31,  pro:1.0, carb:6.0,  fib:2.1, sug:4.2,  fat:0.3, sod:4,   fdc:170108 }]},
  { name:'Cucumber',        cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:15,  pro:0.6, carb:3.6,  fib:0.5, sug:1.7,  fat:0.1, sod:2,   fdc:168409 }]},
  { name:'Celery',          cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:16,  pro:0.7, carb:3.0,  fib:1.6, sug:1.3,  fat:0.2, sod:80,  fdc:169988 }]},
  { name:'Romaine Lettuce', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:17,  pro:1.2, carb:3.3,  fib:2.1, sug:1.2,  fat:0.3, sod:8,   fdc:169247 }]},
  { name:'Zucchini',        cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:17,  pro:1.2, carb:3.1,  fib:1.0, sug:2.5,  fat:0.3, sod:8 }]},
  { name:'Asparagus',       cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:20,  pro:2.2, carb:3.9,  fib:2.1, sug:1.9,  fat:0.1, sod:2 }]},
  { name:'Green Beans',     cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:31,  pro:1.8, carb:7.1,  fib:3.4, sug:3.3,  fat:0.1, sod:6 }]},
  { name:'Corn',            cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:86,  pro:3.3, carb:18.7, fib:2.0, sug:6.3,  fat:1.4, sod:15 }]},
  { name:'White Mushrooms', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:22,  pro:3.1, carb:3.3,  fib:1.0, sug:2.0,  fat:0.3, sod:5 }]},
  { name:'Cauliflower',     cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:25,  pro:1.9, carb:5.0,  fib:2.0, sug:1.9,  fat:0.3, sod:30 }]},
  { name:'Green Onion',     cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:32,  pro:1.8, carb:7.3,  fib:2.6, sug:2.3,  fat:0.2, sod:16 }]},
  // ─── Produce – Fruits ──────────────────────────────────────────────────────
  { name:'Apple',        cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:52,  pro:0.3, carb:13.8, fib:2.4, sug:10.4, fat:0.2, sod:1,  fdc:341508 }]},
  { name:'Banana',       cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:89,  pro:1.1, carb:22.8, fib:2.6, sug:12.2, fat:0.3, sod:1,  fdc:341529 }]},
  { name:'Orange',       cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:47,  pro:0.9, carb:11.8, fib:2.4, sug:9.4,  fat:0.1, sod:0,  fdc:169097 }]},
  { name:'Strawberries', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:32,  pro:0.7, carb:7.7,  fib:2.0, sug:4.9,  fat:0.3, sod:1,  fdc:167762 }]},
  { name:'Blueberries',  cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:57,  pro:0.7, carb:14.5, fib:2.4, sug:10.0, fat:0.3, sod:1,  fdc:171711 }]},
  { name:'Avocado',      cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:160, pro:2.0, carb:8.5,  fib:6.7, sug:0.7,  fat:14.7,sod:7,  fdc:171706 }]},
  { name:'Grapes',       cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:69,  pro:0.7, carb:18.1, fib:0.9, sug:15.5, fat:0.2, sod:2 }]},
  { name:'Lemon',        cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'oz', cal:29,  pro:1.1, carb:9.3,  fib:2.8, sug:2.5,  fat:0.3, sod:2 }]},
  // ─── Pantry – Grains ───────────────────────────────────────────────────────
  { name:'White Rice',   cat:'Baking & Pantry', variants:[{ brand:'Long Grain Dry', sz:100, su:'g', du:'cup', cal:365, pro:7.1,  carb:79.3, fib:1.3,  sug:0.1, fat:0.7, sod:5,  fdc:168878 }]},
  { name:'Brown Rice',   cat:'Baking & Pantry', variants:[{ brand:'Long Grain Dry', sz:100, su:'g', du:'cup', cal:370, pro:7.9,  carb:77.2, fib:3.5,  sug:0.7, fat:2.9, sod:7,  fdc:169704 }]},
  { name:'Pasta',        cat:'Baking & Pantry', variants:[{ brand:'Enriched Dry',   sz:100, su:'g', du:'oz',  cal:371, pro:13.0, carb:74.7, fib:3.2,  sug:2.7, fat:1.5, sod:6,  fdc:168876 }]},
  { name:'Rolled Oats',  cat:'Baking & Pantry', variants:[{ brand:'Generic',        sz:100, su:'g', du:'cup', cal:389, pro:16.9, carb:66.3, fib:10.6, sug:0,   fat:6.9, sod:2,  fdc:168868 }]},
  { name:'Quinoa',       cat:'Baking & Pantry', variants:[{ brand:'Dry',            sz:100, su:'g', du:'cup', cal:368, pro:14.1, carb:64.2, fib:7.0,  sug:0,   fat:6.1, sod:5 }]},
  { name:'Flour Tortilla',cat:'Baking & Pantry', variants:[{ brand:'Generic',       sz:45,  su:'g', du:'each',cal:146, pro:3.8,  carb:25.0, fib:1.3,  sug:1.4, fat:3.5, sod:316 }]},
  { name:'Corn Tortilla', cat:'Baking & Pantry', variants:[{ brand:'Generic',       sz:26,  su:'g', du:'each',cal:52,  pro:1.4,  carb:10.7, fib:1.5,  sug:0.2, fat:0.7, sod:11 }]},
  // ─── Bakery – Bread ────────────────────────────────────────────────────────
  { name:'White Bread',      cat:'Bread & Bakery', peri:true, variants:[{ brand:'Generic', sz:1, su:'slice', du:'slice', cal:79, pro:2.7, carb:14.7, fib:0.6, sug:1.7, fat:1.0, sod:147, fdc:167995 }]},
  { name:'Whole Wheat Bread', cat:'Bread & Bakery', peri:true, variants:[{ brand:'Generic', sz:1, su:'slice', du:'slice', cal:81, pro:3.9, carb:13.6, fib:1.9, sug:2.0, fat:1.1, sod:146, fdc:168014 }]},
  // ─── Pantry – Oils ─────────────────────────────────────────────────────────
  { name:'Olive Oil', cat:'Baking & Pantry', variants:[
    { brand:'Extra Virgin', sz:1, su:'tbsp', du:'tbsp', cal:119, pro:0, carb:0, fib:0, sug:0, fat:13.5, sod:0, fdc:171413 },
    { brand:'Light',        sz:1, su:'tbsp', du:'tbsp', cal:119, pro:0, carb:0, fib:0, sug:0, fat:13.5, sod:0 },
    { brand:'Pure',         sz:1, su:'tbsp', du:'tbsp', cal:119, pro:0, carb:0, fib:0, sug:0, fat:13.5, sod:0 },
  ]},
  { name:'Vegetable Oil', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:1, su:'tbsp', du:'tbsp', cal:124, pro:0, carb:0, fib:0, sug:0, fat:14.0, sod:0 }]},
  // ─── Pantry – Nut Butters & Nuts ───────────────────────────────────────────
  { name:'Peanut Butter', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:2,  su:'tbsp', du:'tbsp', cal:190, pro:7.1, carb:7.1, fib:1.9, sug:3.2, fat:16.0, sod:136, fdc:172470 }]},
  { name:'Almond Butter', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:2,  su:'tbsp', du:'tbsp', cal:196, pro:6.7, carb:6.0, fib:3.3, sug:1.3, fat:18.0, sod:145 }]},
  { name:'Almonds',       cat:'Baking & Pantry', variants:[{ brand:'Raw',     sz:28, su:'g',    du:'oz',   cal:164, pro:6.0, carb:6.1, fib:3.5, sug:1.2, fat:14.2, sod:0,   fdc:170567 }]},
  { name:'Walnuts',       cat:'Baking & Pantry', variants:[{ brand:'Raw',     sz:28, su:'g',    du:'oz',   cal:185, pro:4.3, carb:3.9, fib:1.9, sug:0.7, fat:18.5, sod:1,   fdc:170187 }]},
  // ─── Canned Goods – Legumes ────────────────────────────────────────────────
  { name:'Black Beans', cat:'Canned Goods', variants:[{ brand:'Canned', sz:100, su:'g', du:'oz', cal:91,  pro:5.5, carb:16.6, fib:8.7, sug:0.3, fat:0.5, sod:278 }]},
  { name:'Chickpeas',   cat:'Canned Goods', variants:[{ brand:'Canned', sz:100, su:'g', du:'oz', cal:164, pro:8.9, carb:27.4, fib:7.6, sug:4.8, fat:2.6, sod:288 }]},
  { name:'Lentils',     cat:'Baking & Pantry',       variants:[{ brand:'Cooked', sz:100, su:'g', du:'oz', cal:116, pro:9.0, carb:20.1, fib:7.9, sug:1.8, fat:0.4, sod:2 }]},
  // ─── Pantry – Other ────────────────────────────────────────────────────────
  { name:'Honey',               cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:1,  su:'tbsp', du:'tbsp', cal:64,  pro:0.1,  carb:17.3, fib:0, sug:17.3, fat:0,   sod:1,   fdc:169640 }]},
  { name:'Whey Protein Powder', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:30, su:'g',    du:'oz',   cal:120, pro:25.0, carb:3.0,  fib:0, sug:2.0,  fat:1.5, sod:150 }]},
  // ─── Condiments ────────────────────────────────────────────────────────────
  { name:'Mayonnaise', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:1, su:'tbsp', du:'tbsp', cal:94, pro:0.1, carb:0.1, fib:0, sug:0.1, fat:10.3, sod:84 }]},
  { name:'Ketchup',    cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:1, su:'tbsp', du:'tbsp', cal:18, pro:0.2, carb:4.5, fib:0, sug:3.5, fat:0,    sod:167 }]},
  { name:'Soy Sauce',  cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:1, su:'tbsp', du:'tbsp', cal:9,  pro:1.3, carb:0.8, fib:0, sug:0.1, fat:0.1,  sod:879 }]},
  { name:'Hot Sauce',  cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:1, su:'tsp',  du:'tsp',  cal:1,  pro:0,   carb:0.2, fib:0, sug:0,   fat:0,    sod:124 }]},
  // ─── Seasonings ────────────────────────────────────────────────────────────
  { name:'Salt',              cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:0,  pro:0,   carb:0,   fib:0,   sug:0,   fat:0,   sod:2325 }]},
  { name:'Black Pepper',      cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:6,  pro:0.2, carb:1.4, fib:0.5, sug:0,   fat:0.1, sod:1 }]},
  { name:'Garlic Powder',     cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:10, pro:0.5, carb:2.2, fib:0.3, sug:0.1, fat:0,   sod:2 }]},
  { name:'Onion Powder',      cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:8,  pro:0.2, carb:2.0, fib:0.3, sug:0.1, fat:0,   sod:1 }]},
  { name:'Ground Cumin',      cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:8,  pro:0.4, carb:0.9, fib:0.2, sug:0,   fat:0.5, sod:4 }]},
  { name:'Paprika',           cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:6,  pro:0.3, carb:1.2, fib:0.7, sug:0.2, fat:0.3, sod:2 }]},
  { name:'Chili Powder',      cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:8,  pro:0.3, carb:1.4, fib:0.9, sug:0.1, fat:0.4, sod:77 }]},
  { name:'Italian Seasoning', cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:3,  pro:0.1, carb:0.6, fib:0.3, sug:0,   fat:0.1, sod:1 }]},
  { name:'Ground Cinnamon',   cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:6,  pro:0.1, carb:2.1, fib:1.4, sug:0.1, fat:0,   sod:0 }]},
  { name:'Red Pepper Flakes', cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:6,  pro:0.3, carb:1.1, fib:0.5, sug:0.2, fat:0.3, sod:2 }]},
  { name:'Dried Oregano',     cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:3,  pro:0.1, carb:0.7, fib:0.4, sug:0,   fat:0.1, sod:0 }]},
  { name:'Dried Basil',       cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:1,  pro:0.1, carb:0.3, fib:0.2, sug:0,   fat:0,   sod:0 }]},
  { name:'Dried Thyme',       cat:'Seasonings & Spices', variants:[{ brand:'Generic', sz:1, su:'tsp', du:'tsp', cal:3,  pro:0.1, carb:0.7, fib:0.4, sug:0,   fat:0.1, sod:0 }]},
  // ─── Bakery ────────────────────────────────────────────────────────────────
  { name:'All-Purpose Flour', cat:'Bread & Bakery', variants:[{ brand:'Generic', sz:30, su:'g',    du:'cup', cal:110, pro:3.0, carb:22.9, fib:0.8, sug:0.1, fat:0.3, sod:0,   fdc:169761 }]},
  { name:'Whole Wheat Flour', cat:'Bread & Bakery', variants:[{ brand:'Generic', sz:30, su:'g',    du:'cup', cal:102, pro:4.1, carb:22.0, fib:3.6, sug:0.1, fat:0.6, sod:2 }]},
  { name:'Granulated Sugar',  cat:'Bread & Bakery', variants:[{ brand:'Generic', sz:1,  su:'tsp',  du:'tsp', cal:16,  pro:0,   carb:4.2,  fib:0,   sug:4.2, fat:0,   sod:0,   fdc:169655 }]},
  { name:'Brown Sugar', cat:'Bread & Bakery', variants:[
    { brand:'Light', sz:1, su:'tsp', du:'tsp', cal:15, pro:0, carb:4.0, fib:0, sug:4.0, fat:0, sod:1 },
    { brand:'Dark',  sz:1, su:'tsp', du:'tsp', cal:15, pro:0, carb:4.0, fib:0, sug:4.0, fat:0, sod:1 },
  ]},
  { name:'Baking Powder',   cat:'Bread & Bakery', variants:[{ brand:'Generic', sz:1, su:'tsp',  du:'tsp',  cal:2,  pro:0,   carb:1.1, fib:0,   sug:0,   fat:0,   sod:488 }]},
  { name:'Cocoa Powder',    cat:'Bread & Bakery', variants:[{ brand:'Generic', sz:1, su:'tbsp', du:'tbsp', cal:12, pro:1.1, carb:3.0, fib:2.0, sug:0.1, fat:0.7, sod:1 }]},
  { name:'Vanilla Extract', cat:'Bread & Bakery', variants:[{ brand:'Generic', sz:1, su:'tsp',  du:'tsp',  cal:12, pro:0,   carb:0.5, fib:0,   sug:0.5, fat:0,   sod:1 }]},
  // ─── Beverages ─────────────────────────────────────────────────────────────
  { name:'Water',          cat:'Beverages', variants:[{ brand:'Generic', sz:240, su:'ml', du:'cup', cal:0,   pro:0,   carb:0,    fib:0,   sug:0,    fat:0,   sod:7 }]},
  { name:'Orange Juice',   cat:'Beverages', variants:[{ brand:'Generic', sz:240, su:'ml', du:'cup', cal:112, pro:1.7, carb:26.0, fib:0.5, sug:20.8, fat:0.5, sod:2 }]},
  { name:'Apple Juice',    cat:'Beverages', variants:[{ brand:'Generic', sz:240, su:'ml', du:'cup', cal:114, pro:0.2, carb:28.0, fib:0.2, sug:23.9, fat:0.3, sod:7 }]},
  { name:'Coffee (Black)', cat:'Beverages', variants:[{ brand:'Generic', sz:240, su:'ml', du:'cup', cal:2,   pro:0.3, carb:0,    fib:0,   sug:0,    fat:0,   sod:5 }]},
  // ─── USDA Comprehensive Set (added 2026-07-24, 339 new items merged in) ───
  // ─── Meat & Poultry ───
  { name:'Chicken Breast Boneless Skinless Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:132, pro:27.3, carb:0, fib:0, sug:0, fat:2.9, sod:74 }]},
  { name:'Chicken Breast Bone-In Skin-On Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:189, pro:19, carb:0, fib:0, sug:0, fat:12, sod:68 }]},
  { name:'Chicken Thigh Boneless Skinless Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:153, pro:20.3, carb:0, fib:0, sug:0, fat:8, sod:88 }]},
  { name:'Chicken Thigh Bone-In Skin-On Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:229, pro:18, carb:0, fib:0, sug:0, fat:16, sod:82 }]},
  { name:'Chicken Drumstick Bone-In Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:143, pro:18.7, carb:0, fib:0, sug:0, fat:7.4, sod:90 }]},
  { name:'Chicken Wing Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:203, pro:17.3, carb:0, fib:0, sug:0, fat:14.4, sod:85 }]},
  { name:'Chicken Tenderloin Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:124, pro:26.2, carb:0, fib:0, sug:0, fat:2.1, sod:73 }]},
  { name:'Whole Chicken Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:215, pro:18.5, carb:0, fib:0, sug:0, fat:15.3, sod:78 }]},
  { name:'Ground Chicken Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:170, pro:20.4, carb:0, fib:0, sug:0, fat:9.5, sod:84 }]},
  { name:'Ground Turkey 93/7 Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:170, pro:22.4, carb:0, fib:0, sug:0, fat:9, sod:80 }]},
  { name:'Ground Turkey 85/15 Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:220, pro:20, carb:0, fib:0, sug:0, fat:15, sod:85 }]},
  { name:'Turkey Breast Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:133, pro:28.3, carb:0, fib:0, sug:0, fat:1.8, sod:63 }]},
  { name:'Turkey Thigh Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:194, pro:20.7, carb:0, fib:0, sug:0, fat:12, sod:82 }]},
  { name:'Ground Beef 70/30 Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:332, pro:14.3, carb:0, fib:0, sug:0, fat:30, sod:70 }]},
  { name:'Ground Beef 80/20 Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:287, pro:18.7, carb:0, fib:0, sug:0, fat:23, sod:75 }]},
  { name:'Ground Beef 85/15 Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:243, pro:20.7, carb:0, fib:0, sug:0, fat:17.3, sod:75 }]},
  { name:'Ground Beef 90/10 Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:196, pro:23.3, carb:0, fib:0, sug:0, fat:11, sod:77 }]},
  { name:'Ground Beef 93/7 Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:160, pro:24, carb:0, fib:0, sug:0, fat:7, sod:77 }]},
  { name:'Beef Chuck Roast Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:215, pro:20.3, carb:0, fib:0, sug:0, fat:14.3, sod:60 }]},
  { name:'Beef Ribeye Steak Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:291, pro:19.3, carb:0, fib:0, sug:0, fat:23.3, sod:57 }]},
  { name:'Beef Sirloin Steak Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:188, pro:23.7, carb:0, fib:0, sug:0, fat:10, sod:63 }]},
  { name:'Beef Tenderloin Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:204, pro:21.7, carb:0, fib:0, sug:0, fat:12.7, sod:57 }]},
  { name:'Beef Brisket Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:237, pro:19.7, carb:0, fib:0, sug:0, fat:17.3, sod:63 }]},
  { name:'Beef Short Ribs Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:299, pro:16.3, carb:0, fib:0, sug:0, fat:25.7, sod:53 }]},
  { name:'Beef Flank Steak Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:187, pro:24, carb:0, fib:0, sug:0, fat:9.7, sod:73 }]},
  { name:'Beef Skirt Steak Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:200, pro:22.7, carb:0, fib:0, sug:0, fat:12, sod:67 }]},
  { name:'Beef T-Bone Steak Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:230, pro:20.3, carb:0, fib:0, sug:0, fat:16.3, sod:57 }]},
  { name:'Beef Strip Steak NY Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:205, pro:22.7, carb:0, fib:0, sug:0, fat:12.7, sod:60 }]},
  { name:'Stew Beef Cubed Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:186, pro:22, carb:0, fib:0, sug:0, fat:10.7, sod:57 }]},
  { name:'Ground Pork Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:252, pro:17.7, carb:0, fib:0, sug:0, fat:20, sod:60 }]},
  { name:'Pork Chop Boneless Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:187, pro:23, carb:0, fib:0, sug:0, fat:10, sod:57 }]},
  { name:'Pork Chop Bone-In Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:211, pro:21, carb:0, fib:0, sug:0, fat:13.3, sod:60 }]},
  { name:'Pork Tenderloin Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:136, pro:23.7, carb:0, fib:0, sug:0, fat:4, sod:57 }]},
  { name:'Pork Loin Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:178, pro:22.3, carb:0, fib:0, sug:0, fat:9.3, sod:57 }]},
  { name:'Pork Shoulder Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:258, pro:18.3, carb:0, fib:0, sug:0, fat:20.3, sod:63 }]},
  { name:'Pork Ribs Baby Back Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:315, pro:17, carb:0, fib:0, sug:0, fat:27, sod:63 }]},
  { name:'Pork Ribs Spare Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:334, pro:16.7, carb:0, fib:0, sug:0, fat:29.3, sod:63 }]},
  { name:'Pork Belly Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:518, pro:9.3, carb:0, fib:0, sug:0, fat:53.3, sod:25 }]},
  { name:'Bacon Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:107, pro:3.3, carb:0.1, fib:0, sug:0, fat:10, sod:233 }]},
  { name:'Bacon Cooked', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:12, su:'g', du:'g', cal:54, pro:3.7, carb:0.1, fib:0, sug:0, fat:4.3, sod:194 }]},
  { name:'Ground Lamb Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:283, pro:17, carb:0, fib:0, sug:0, fat:23.3, sod:73 }]},
  { name:'Lamb Chop Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:274, pro:17.3, carb:0, fib:0, sug:0, fat:22.3, sod:73 }]},
  { name:'Lamb Leg Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:215, pro:20, carb:0, fib:0, sug:0, fat:14.7, sod:70 }]},
  { name:'Veal Ground Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:172, pro:20.3, carb:0, fib:0, sug:0, fat:9.7, sod:80 }]},
  { name:'Veal Cutlet Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:150, pro:22.7, carb:0, fib:0, sug:0, fat:6.3, sod:87 }]},
  { name:'Ground Bison Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:152, pro:22.7, carb:0, fib:0, sug:0, fat:6.7, sod:60 }]},
  { name:'Ground Venison Raw', cat:'Meat & Poultry', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:159, pro:22.3, carb:0, fib:0, sug:0, fat:7.3, sod:57 }]},
  // ─── Seafood ───
  { name:'Salmon Atlantic Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:208, pro:20.3, carb:0, fib:0, sug:0, fat:13.3, sod:59 }]},
  { name:'Salmon Sockeye Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:158, pro:22.3, carb:0, fib:0, sug:0, fat:7.7, sod:53 }]},
  { name:'Salmon Pink Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:130, pro:22, carb:0, fib:0, sug:0, fat:4.3, sod:67 }]},
  { name:'Tilapia Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:110, pro:23, carb:0, fib:0, sug:0, fat:2, sod:52 }]},
  { name:'Cod Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:90, pro:19.7, carb:0, fib:0, sug:0, fat:0.7, sod:73 }]},
  { name:'Halibut Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:124, pro:23.7, carb:0, fib:0, sug:0, fat:2.7, sod:73 }]},
  { name:'Mahi Mahi Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:99, pro:21.3, carb:0, fib:0, sug:0, fat:0.8, sod:100 }]},
  { name:'Catfish Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:119, pro:18.7, carb:0, fib:0, sug:0, fat:4.7, sod:50 }]},
  { name:'Bass Striped Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:110, pro:20, carb:0, fib:0, sug:0, fat:2.7, sod:77 }]},
  { name:'Snapper Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:113, pro:23.3, carb:0, fib:0, sug:0, fat:1.5, sod:73 }]},
  { name:'Trout Rainbow Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:156, pro:22.3, carb:0, fib:0, sug:0, fat:7, sod:50 }]},
  { name:'Flounder Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:91, pro:18.7, carb:0, fib:0, sug:0, fat:1.2, sod:80 }]},
  { name:'Pollock Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:92, pro:20, carb:0, fib:0, sug:0, fat:1, sod:90 }]},
  { name:'Shrimp Raw Peeled', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:120, pro:23, carb:1, fib:0, sug:0, fat:2, sod:168 }]},
  { name:'Shrimp Cooked', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:112, pro:23.7, carb:0, fib:0, sug:0, fat:1.2, sod:254 }]},
  { name:'Crab Dungeness Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:87, pro:17.7, carb:0.7, fib:0, sug:0, fat:1, sod:333 }]},
  { name:'Crab King Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:84, pro:18.3, carb:0, fib:0, sug:0, fat:0.5, sod:836 }]},
  { name:'Lobster Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:90, pro:18.7, carb:0.5, fib:0, sug:0, fat:0.9, sod:323 }]},
  { name:'Scallops Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:100, pro:19, carb:4.7, fib:0, sug:0, fat:0.9, sod:370 }]},
  { name:'Clams Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:63, pro:10.9, carb:2.2, fib:0, sug:0, fat:0.8, sod:473 }]},
  { name:'Oysters Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:69, pro:7.1, carb:3.9, fib:0, sug:0, fat:2.5, sod:210 }]},
  { name:'Mussels Raw', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:73, pro:10.1, carb:3.1, fib:0, sug:0, fat:1.9, sod:243 }]},
  { name:'Sardines in Water Canned', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:130, pro:17.3, carb:0, fib:0, sug:0, fat:6.3, sod:282 }]},
  { name:'Tuna Canned in Water', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:73, pro:16.7, carb:0, fib:0, sug:0, fat:0.5, sod:212 }]},
  { name:'Tuna Canned in Oil', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:168, pro:24.7, carb:0, fib:0, sug:0, fat:7, sod:301 }]},
  { name:'Salmon Canned', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:130, pro:17.7, carb:0, fib:0, sug:0, fat:6.7, sod:320 }]},
  { name:'Anchovies Canned', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:20, su:'g', du:'g', cal:42, pro:5.8, carb:0, fib:0, sug:0, fat:1.9, sod:734 }]},
  { name:'Imitation Crab', cat:'Seafood', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:81, pro:6.4, carb:13, fib:0, sug:5.2, fat:0.4, sod:715 }]},
  // ─── Eggs ───
  { name:'Egg Large Whole', cat:'Eggs', peri:true, variants:[{ brand:'Generic', sz:50, su:'g', du:'g', cal:72, pro:6.3, carb:0.4, fib:0, sug:0.2, fat:4.8, sod:71 }]},
  { name:'Egg Large White Only', cat:'Eggs', peri:true, variants:[{ brand:'Generic', sz:33, su:'g', du:'g', cal:17, pro:3.6, carb:0.2, fib:0, sug:0.2, fat:0.1, sod:55 }]},
  { name:'Egg Large Yolk Only', cat:'Eggs', peri:true, variants:[{ brand:'Generic', sz:17, su:'g', du:'g', cal:55, pro:2.7, carb:0.6, fib:0, sug:0.1, fat:4.5, sod:8 }]},
  { name:'Egg Extra Large', cat:'Eggs', peri:true, variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:80, pro:7, carb:0.4, fib:0, sug:0.2, fat:5.3, sod:80 }]},
  { name:'Egg Medium', cat:'Eggs', peri:true, variants:[{ brand:'Generic', sz:44, su:'g', du:'g', cal:63, pro:5.5, carb:0.3, fib:0, sug:0.2, fat:4.2, sod:63 }]},
  // ─── Dairy ───
  { name:'Milk Whole', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:244, su:'ml', du:'ml', cal:149, pro:7.7, carb:11.7, fib:0, sug:12.3, fat:8, sod:105 }]},
  { name:'Milk 2 Percent', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:244, su:'ml', du:'ml', cal:122, pro:8.1, carb:11.7, fib:0, sug:12.3, fat:4.8, sod:115 }]},
  { name:'Milk 1 Percent', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:244, su:'ml', du:'ml', cal:102, pro:8.2, carb:12.2, fib:0, sug:12.7, fat:2.4, sod:107 }]},
  { name:'Milk Skim Nonfat', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:244, su:'ml', du:'ml', cal:83, pro:8.3, carb:12.2, fib:0, sug:12.5, fat:0.2, sod:103 }]},
  { name:'Buttermilk', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:244, su:'ml', du:'ml', cal:99, pro:8.1, carb:11.7, fib:0, sug:12, fat:2.2, sod:257 }]},
  { name:'Heavy Whipping Cream', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:30, su:'ml', du:'ml', cal:101, pro:0.6, carb:0.8, fib:0, sug:0, fat:10.6, sod:11 }]},
  { name:'Half and Half', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:30, su:'ml', du:'ml', cal:39, pro:0.9, carb:1.3, fib:0, sug:0.1, fat:3.5, sod:12 }]},
  { name:'Cream Cheese Fat Free', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:29, su:'g', du:'g', cal:30, pro:4.3, carb:1.9, fib:0, sug:0.9, fat:0.5, sod:171 }]},
  { name:'Butter Salted', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:102, pro:0.1, carb:0, fib:0, sug:0, fat:11.5, sod:91 }]},
  { name:'Butter Unsalted', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:102, pro:0.1, carb:0, fib:0, sug:0, fat:11.5, sod:2 }]},
  { name:'Ghee', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:130, pro:0, carb:0, fib:0, sug:0, fat:14.5, sod:0 }]},
  { name:'Mozzarella Whole Milk', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:85, pro:6.3, carb:0.6, fib:0, sug:0.3, fat:6.3, sod:138 }]},
  { name:'Mozzarella Part Skim', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:72, pro:6.9, carb:0.8, fib:0, sug:0.3, fat:4.5, sod:175 }]},
  { name:'Parmesan Grated', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:10, su:'g', du:'g', cal:42, pro:3.8, carb:0.4, fib:0, sug:0.1, fat:2.8, sod:165 }]},
  { name:'Swiss Cheese', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:108, pro:7.7, carb:1.5, fib:0, sug:0.5, fat:7.9, sod:54 }]},
  { name:'Provolone Cheese', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:100, pro:7.3, carb:0.6, fib:0, sug:0.1, fat:7.6, sod:248 }]},
  { name:'Colby Jack Cheese', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:110, pro:6.7, carb:0.4, fib:0, sug:0.1, fat:9, sod:170 }]},
  { name:'Pepper Jack Cheese', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:110, pro:6.7, carb:0.3, fib:0, sug:0.3, fat:9, sod:180 }]},
  { name:'American Cheese', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:94, pro:5.5, carb:1.3, fib:0, sug:0.8, fat:7.1, sod:406 }]},
  { name:'Ricotta Whole Milk', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:62, su:'g', du:'g', cal:107, pro:6.9, carb:2, fib:0, sug:0.3, fat:8, sod:52 }]},
  { name:'Ricotta Part Skim', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:62, su:'g', du:'g', cal:85, pro:7.1, carb:3.2, fib:0, sug:0.4, fat:4.9, sod:77 }]},
  { name:'Cottage Cheese 4 Percent', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:110, pro:12.5, carb:3.4, fib:0, sug:3.4, fat:5, sod:379 }]},
  { name:'Cottage Cheese 2 Percent', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:90, pro:13, carb:3.7, fib:0, sug:3.6, fat:2.5, sod:420 }]},
  { name:'Cottage Cheese 1 Percent', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:81, pro:14, carb:3, fib:0, sug:3, fat:1.2, sod:459 }]},
  { name:'Greek Yogurt Plain Nonfat', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:170, su:'g', du:'g', cal:100, pro:17.3, carb:5.7, fib:0, sug:5.7, fat:0.7, sod:65 }]},
  { name:'Greek Yogurt Plain Whole Milk', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:170, su:'g', du:'g', cal:130, pro:11.3, carb:5.3, fib:0, sug:5.3, fat:6.7, sod:55 }]},
  { name:'Greek Yogurt Plain 2 Percent', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:170, su:'g', du:'g', cal:110, pro:14.7, carb:5.3, fib:0, sug:5.3, fat:3, sod:60 }]},
  { name:'Yogurt Plain Whole Milk', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:245, su:'g', du:'g', cal:149, pro:8.5, carb:11.4, fib:0, sug:11.4, fat:8, sod:113 }]},
  { name:'Yogurt Plain Nonfat', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:245, su:'g', du:'g', cal:137, pro:14, carb:18.8, fib:0, sug:18.8, fat:0.4, sod:189 }]},
  { name:'Almond Milk Unsweetened', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:30, pro:1, carb:1, fib:0.5, sug:0, fat:2.5, sod:160 }]},
  { name:'Oat Milk', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:120, pro:3, carb:16, fib:2, sug:7, fat:5, sod:100 }]},
  { name:'Soy Milk Unsweetened', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:80, pro:7, carb:4, fib:1, sug:1, fat:4, sod:90 }]},
  { name:'Coconut Milk Canned', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:60, su:'ml', du:'ml', cal:120, pro:1.2, carb:2.7, fib:0, sug:0.8, fat:12, sod:15 }]},
  { name:'Coconut Milk Beverage', cat:'Dairy', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:45, pro:0.5, carb:1, fib:0, sug:0, fat:4.5, sod:45 }]},
  { name:'Butter Clarified Ghee', cat:'Dairy', variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:130, pro:0, carb:0, fib:0, sug:0, fat:14.5, sod:0 }]},
  // ─── Produce ───
  { name:'Apple Green (Granny Smith)', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:182, su:'g', du:'g', cal:80, pro:0.4, carb:21.3, fib:3.8, sug:15, fat:0.3, sod:2 }]},
  { name:'Lime', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:67, su:'g', du:'g', cal:20, pro:0.5, carb:7.1, fib:1.9, sug:1.1, fat:0.1, sod:1 }]},
  { name:'Raspberries', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:123, su:'g', du:'g', cal:64, pro:1.5, carb:14.7, fib:8, sug:5.4, fat:0.8, sod:1 }]},
  { name:'Blackberries', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:144, su:'g', du:'g', cal:62, pro:2, carb:13.8, fib:7.6, sug:7, fat:0.7, sod:1 }]},
  { name:'Grapes Red', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:151, su:'g', du:'g', cal:104, pro:1.1, carb:27.3, fib:1.4, sug:23.4, fat:0.2, sod:3 }]},
  { name:'Grapes Green', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:151, su:'g', du:'g', cal:104, pro:1.1, carb:27.2, fib:1.4, sug:23.4, fat:0.2, sod:3 }]},
  { name:'Watermelon', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:280, su:'g', du:'g', cal:85, pro:1.7, carb:21.3, fib:1.1, sug:17.7, fat:0.4, sod:3 }]},
  { name:'Cantaloupe', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:177, su:'g', du:'g', cal:60, pro:1.5, carb:14.4, fib:1.6, sug:13.8, fat:0.3, sod:28 }]},
  { name:'Honeydew Melon', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:177, su:'g', du:'g', cal:64, pro:0.9, carb:16.1, fib:1.4, sug:14.4, fat:0.3, sod:32 }]},
  { name:'Pineapple', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:165, su:'g', du:'g', cal:82, pro:0.9, carb:21.6, fib:2.3, sug:16.3, fat:0.2, sod:2 }]},
  { name:'Mango', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:165, su:'g', du:'g', cal:99, pro:1.4, carb:24.7, fib:2.6, sug:22.5, fat:0.6, sod:2 }]},
  { name:'Peach', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:150, su:'g', du:'g', cal:58, pro:1.4, carb:14.3, fib:2.3, sug:12.9, fat:0.4, sod:0 }]},
  { name:'Pear', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:178, su:'g', du:'g', cal:101, pro:0.6, carb:27.1, fib:5.5, sug:17.4, fat:0.2, sod:2 }]},
  { name:'Plum', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:66, su:'g', du:'g', cal:30, pro:0.5, carb:7.5, fib:0.9, sug:6.6, fat:0.2, sod:0 }]},
  { name:'Cherry Sweet', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:138, su:'g', du:'g', cal:87, pro:1.5, carb:22.1, fib:2.9, sug:17.7, fat:0.3, sod:0 }]},
  { name:'Kiwi', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:177, su:'g', du:'g', cal:108, pro:2.1, carb:25.9, fib:5.3, sug:15.9, fat:0.9, sod:5 }]},
  { name:'Avocado Half', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:68, su:'g', du:'g', cal:109, pro:1.3, carb:5.8, fib:4.6, sug:0.5, fat:10, sod:5 }]},
  { name:'Grapefruit', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:230, su:'g', du:'g', cal:74, pro:1.5, carb:18.6, fib:2.5, sug:16.1, fat:0.2, sod:0 }]},
  { name:'Papaya', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:145, su:'g', du:'g', cal:62, pro:0.7, carb:15.7, fib:2.5, sug:11.3, fat:0.4, sod:12 }]},
  { name:'Pomegranate Seeds', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:87, su:'g', du:'g', cal:72, pro:1.5, carb:16.3, fib:3.5, sug:11.9, fat:1, sod:3 }]},
  { name:'Cranberries Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:110, su:'g', du:'g', cal:46, pro:0.4, carb:12.2, fib:4.6, sug:4, fat:0.1, sod:2 }]},
  { name:'Apricot', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:35, su:'g', du:'g', cal:17, pro:0.5, carb:3.9, fib:0.7, sug:3.2, fat:0.1, sod:0 }]},
  { name:'Nectarine', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:136, su:'g', du:'g', cal:57, pro:1.4, carb:13.6, fib:2.2, sug:11.2, fat:0.4, sod:0 }]},
  { name:'Fig Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:50, su:'g', du:'g', cal:37, pro:0.4, carb:9.6, fib:1.5, sug:8.1, fat:0.1, sod:1 }]},
  { name:'Coconut Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:45, su:'g', du:'g', cal:159, pro:1.5, carb:6.8, fib:4, sug:2.8, fat:15.1, sod:9 }]},
  { name:'Dates Medjool', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:24, su:'g', du:'g', cal:66, pro:0.4, carb:18, fib:1.6, sug:16, fat:0, sod:0 }]},
  { name:'Raisins', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:43, su:'g', du:'g', cal:129, pro:1.4, carb:34.1, fib:1.9, sug:25.4, fat:0.2, sod:5 }]},
  { name:'Spinach Raw', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:30, su:'g', du:'g', cal:7, pro:0.9, carb:1.1, fib:0.7, sug:0.1, fat:0.1, sod:24 }]},
  { name:'Spinach Cooked', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:180, su:'g', du:'g', cal:41, pro:5.4, carb:6.8, fib:4.3, sug:0.8, fat:0.5, sod:126 }]},
  { name:'Kale Raw', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:67, su:'g', du:'g', cal:34, pro:2.2, carb:6.7, fib:1.3, sug:1.6, fat:0.5, sod:29 }]},
  { name:'Lettuce Romaine', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:47, su:'g', du:'g', cal:8, pro:0.6, carb:1.5, fib:1, sug:0.5, fat:0.1, sod:4 }]},
  { name:'Lettuce Iceberg', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:72, su:'g', du:'g', cal:10, pro:0.6, carb:2, fib:0.7, sug:1.3, fat:0.1, sod:7 }]},
  { name:'Arugula', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:20, su:'g', du:'g', cal:5, pro:0.5, carb:0.7, fib:0.3, sug:0.4, fat:0.1, sod:5 }]},
  { name:'Cabbage Green', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:89, su:'g', du:'g', cal:22, pro:1.1, carb:5.2, fib:2.2, sug:2.8, fat:0.1, sod:16 }]},
  { name:'Cabbage Red', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:89, su:'g', du:'g', cal:28, pro:1.3, carb:6.6, fib:1.9, sug:3.5, fat:0.1, sod:19 }]},
  { name:'Brussels Sprouts', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:88, su:'g', du:'g', cal:38, pro:3, carb:7.9, fib:3.3, sug:1.9, fat:0.3, sod:22 }]},
  { name:'Carrot', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:61, su:'g', du:'g', cal:25, pro:0.6, carb:5.8, fib:1.7, sug:2.9, fat:0.1, sod:42 }]},
  { name:'Carrot Baby', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:85, su:'g', du:'g', cal:35, pro:0.6, carb:8.2, fib:2.3, sug:4.7, fat:0.1, sod:63 }]},
  { name:'Yellow Squash', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:113, su:'g', du:'g', cal:19, pro:1.4, carb:4, fib:1.2, sug:2.2, fat:0.2, sod:2 }]},
  { name:'Butternut Squash', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:140, su:'g', du:'g', cal:63, pro:1.4, carb:16.4, fib:2.8, sug:3.1, fat:0.1, sod:6 }]},
  { name:'Acorn Squash', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:172, su:'g', du:'g', cal:56, pro:1.1, carb:14.6, fib:2.1, sug:0, fat:0.1, sod:4 }]},
  { name:'Tomato Cherry', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:149, su:'g', du:'g', cal:27, pro:1.3, carb:5.8, fib:1.8, sug:3.9, fat:0.3, sod:7 }]},
  { name:'Tomato Roma', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:62, su:'g', du:'g', cal:11, pro:0.5, carb:2.4, fib:0.7, sug:1.6, fat:0.1, sod:3 }]},
  { name:'Bell Pepper Red', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:119, su:'g', du:'g', cal:37, pro:1.2, carb:7.2, fib:2.5, sug:4.9, fat:0.4, sod:6 }]},
  { name:'Bell Pepper Green', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:119, su:'g', du:'g', cal:24, pro:1, carb:5.5, fib:2, sug:2.9, fat:0.2, sod:4 }]},
  { name:'Bell Pepper Yellow', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:119, su:'g', du:'g', cal:50, pro:1.9, carb:11.8, fib:1.7, sug:7.5, fat:0.4, sod:4 }]},
  { name:'Bell Pepper Orange', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:119, su:'g', du:'g', cal:45, pro:1.5, carb:10.5, fib:1.9, sug:6.3, fat:0.3, sod:3 }]},
  { name:'Jalapeno Pepper', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:4, pro:0.1, carb:0.9, fib:0.4, sug:0.6, fat:0.1, sod:0 }]},
  { name:'Serrano Pepper', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:6, su:'g', du:'g', cal:2, pro:0.1, carb:0.4, fib:0.1, sug:0.2, fat:0, sod:0 }]},
  { name:'Poblano Pepper', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:17, su:'g', du:'g', cal:5, pro:0.2, carb:1.1, fib:0.4, sug:0.6, fat:0.1, sod:1 }]},
  { name:'Onion Yellow', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:110, su:'g', du:'g', cal:44, pro:1.2, carb:10.3, fib:1.9, sug:4.7, fat:0.1, sod:4 }]},
  { name:'Onion Red', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:110, su:'g', du:'g', cal:46, pro:1.3, carb:10.7, fib:1.5, sug:5.1, fat:0.1, sod:5 }]},
  { name:'Onion White', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:110, su:'g', du:'g', cal:44, pro:1.2, carb:10.3, fib:1.9, sug:4.7, fat:0.1, sod:4 }]},
  { name:'Green Onion Scallion', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:15, su:'g', du:'g', cal:5, pro:0.3, carb:1.1, fib:0.4, sug:0.4, fat:0, sod:5 }]},
  { name:'Garlic Clove', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:3, su:'g', du:'g', cal:4, pro:0.2, carb:1, fib:0.1, sug:0, fat:0, sod:1 }]},
  { name:'Shallot', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:10, su:'g', du:'g', cal:7, pro:0.3, carb:1.7, fib:0.3, sug:0.8, fat:0, sod:1 }]},
  { name:'Leek', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:89, su:'g', du:'g', cal:54, pro:1.3, carb:12.6, fib:1.6, sug:3.5, fat:0.3, sod:18 }]},
  { name:'Potato Russet', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:213, su:'g', du:'g', cal:168, pro:4.6, carb:38.1, fib:2.6, sug:1.3, fat:0.2, sod:11 }]},
  { name:'Potato Red', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:213, su:'g', du:'g', cal:154, pro:4.2, carb:34.7, fib:3.2, sug:2.6, fat:0.3, sod:22 }]},
  { name:'Potato Gold Yukon', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:148, su:'g', du:'g', cal:110, pro:3, carb:26, fib:2, sug:1, fat:0, sod:8 }]},
  { name:'Yam', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:136, su:'g', du:'g', cal:158, pro:2, carb:37.5, fib:5.3, sug:0.6, fat:0.2, sod:11 }]},
  { name:'Corn on the Cob', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:90, su:'g', du:'g', cal:77, pro:2.9, carb:17.1, fib:1.8, sug:2.9, fat:1.1, sod:14 }]},
  { name:'Corn Kernels Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:154, su:'g', du:'g', cal:132, pro:4.9, carb:29, fib:3.2, sug:5, fat:1.8, sod:23 }]},
  { name:'Snow Peas', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:98, su:'g', du:'g', cal:41, pro:2.8, carb:7.4, fib:2.5, sug:3.8, fat:0.2, sod:4 }]},
  { name:'Edamame Shelled', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:155, su:'g', du:'g', cal:188, pro:18.4, carb:13.8, fib:8.1, sug:3.4, fat:8.1, sod:9 }]},
  { name:'Peas Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:145, su:'g', du:'g', cal:117, pro:7.9, carb:20.9, fib:7.4, sug:8.2, fat:0.6, sod:7 }]},
  { name:'Artichoke', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:120, su:'g', du:'g', cal:60, pro:4.2, carb:13.4, fib:6.5, sug:1.3, fat:0.2, sod:120 }]},
  { name:'Beets', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:136, su:'g', du:'g', cal:58, pro:2.2, carb:13, fib:2.6, sug:9.2, fat:0.2, sod:106 }]},
  { name:'Turnip', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:130, su:'g', du:'g', cal:36, pro:1.2, carb:8.4, fib:2.3, sug:4.9, fat:0.1, sod:87 }]},
  { name:'Radish', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:116, su:'g', du:'g', cal:19, pro:0.8, carb:3.9, fib:1.9, sug:2.2, fat:0.1, sod:45 }]},
  { name:'Mushroom White Button', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:70, su:'g', du:'g', cal:15, pro:2.2, carb:2.3, fib:0.7, sug:1.4, fat:0.2, sod:4 }]},
  { name:'Mushroom Portobello', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:84, su:'g', du:'g', cal:19, pro:1.8, carb:3.3, fib:1.1, sug:2.2, fat:0.3, sod:9 }]},
  { name:'Mushroom Cremini', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:70, su:'g', du:'g', cal:16, pro:2.2, carb:2.5, fib:0.6, sug:1.5, fat:0.2, sod:9 }]},
  { name:'Mushroom Shiitake', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:70, su:'g', du:'g', cal:27, pro:1.9, carb:6.8, fib:2.5, sug:1.7, fat:0.4, sod:3 }]},
  { name:'Eggplant', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:82, su:'g', du:'g', cal:20, pro:0.8, carb:4.8, fib:2.5, sug:2.9, fat:0.1, sod:2 }]},
  { name:'Okra', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:100, su:'g', du:'g', cal:33, pro:1.9, carb:7.5, fib:3.2, sug:1.5, fat:0.2, sod:7 }]},
  { name:'Bok Choy', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:70, su:'g', du:'g', cal:9, pro:1.1, carb:1.5, fib:0.7, sug:0.8, fat:0.1, sod:46 }]},
  { name:'Collard Greens', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:36, su:'g', du:'g', cal:12, pro:1, carb:2.2, fib:1.4, sug:0.3, fat:0.2, sod:7 }]},
  { name:'Swiss Chard', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:36, su:'g', du:'g', cal:7, pro:0.7, carb:1.3, fib:0.6, sug:0.4, fat:0.1, sod:77 }]},
  { name:'Beet Greens', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:38, su:'g', du:'g', cal:9, pro:0.9, carb:1.8, fib:1.4, sug:0.3, fat:0.1, sod:77 }]},
  { name:'Watercress', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:34, su:'g', du:'g', cal:4, pro:0.8, carb:0.4, fib:0.2, sug:0.1, fat:0, sod:14 }]},
  { name:'Fennel Bulb', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:87, su:'g', du:'g', cal:27, pro:1.1, carb:6.3, fib:2.7, sug:3.4, fat:0.2, sod:45 }]},
  { name:'Kohlrabi', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:135, su:'g', du:'g', cal:36, pro:2.3, carb:8.4, fib:4.9, sug:3.5, fat:0.1, sod:27 }]},
  { name:'Parsnip', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:133, su:'g', du:'g', cal:100, pro:1.6, carb:24, fib:6.5, sug:6.4, fat:0.4, sod:13 }]},
  { name:'Rutabaga', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:140, su:'g', du:'g', cal:52, pro:1.7, carb:11.9, fib:3.5, sug:6.3, fat:0.3, sod:28 }]},
  { name:'Jicama', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:130, su:'g', du:'g', cal:49, pro:0.9, carb:11.4, fib:5.9, sug:2.3, fat:0.1, sod:5 }]},
  { name:'Celery Root', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:156, su:'g', du:'g', cal:66, pro:2.3, carb:14.4, fib:2.8, sug:2.6, fat:0.5, sod:156 }]},
  { name:'Water Chestnut Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:17, pro:0.3, carb:3.9, fib:0.6, sug:0.9, fat:0, sod:5 }]},
  { name:'Cilantro Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:4, su:'g', du:'g', cal:1, pro:0.1, carb:0.1, fib:0.1, sug:0, fat:0, sod:2 }]},
  { name:'Parsley Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:4, su:'g', du:'g', cal:1, pro:0.1, carb:0.2, fib:0.1, sug:0, fat:0, sod:2 }]},
  { name:'Basil Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:2, su:'g', du:'g', cal:1, pro:0.1, carb:0.1, fib:0, sug:0, fat:0, sod:0 }]},
  { name:'Mint Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:2, su:'g', du:'g', cal:1, pro:0.1, carb:0.1, fib:0.1, sug:0, fat:0, sod:1 }]},
  { name:'Rosemary Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:2, su:'g', du:'g', cal:3, pro:0.1, carb:0.6, fib:0.4, sug:0, fat:0.1, sod:0 }]},
  { name:'Thyme Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:1, su:'g', du:'g', cal:1, pro:0.1, carb:0.2, fib:0.1, sug:0, fat:0, sod:0 }]},
  { name:'Oregano Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:2, su:'g', du:'g', cal:1, pro:0.1, carb:0.3, fib:0.2, sug:0, fat:0, sod:0 }]},
  { name:'Dill Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:3, su:'g', du:'g', cal:1, pro:0.1, carb:0.1, fib:0, sug:0.1, fat:0, sod:2 }]},
  { name:'Chives Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:3, su:'g', du:'g', cal:1, pro:0.1, carb:0.1, fib:0.1, sug:0, fat:0, sod:0 }]},
  { name:'Sage Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:2, su:'g', du:'g', cal:3, pro:0.1, carb:0.6, fib:0.4, sug:0, fat:0.1, sod:0 }]},
  { name:'Tarragon Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:2, su:'g', du:'g', cal:2, pro:0.1, carb:0.3, fib:0.1, sug:0, fat:0, sod:1 }]},
  { name:'Bay Leaves Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:1, su:'g', du:'g', cal:3, pro:0.1, carb:0.7, fib:0.2, sug:0, fat:0.1, sod:0 }]},
  { name:'Lemongrass Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:6, su:'g', du:'g', cal:5, pro:0.1, carb:1.2, fib:0, sug:0, fat:0, sod:1 }]},
  { name:'Ginger Root Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:6, su:'g', du:'g', cal:5, pro:0.1, carb:1.1, fib:0.1, sug:0.1, fat:0, sod:1 }]},
  { name:'Turmeric Root Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:7, su:'g', du:'g', cal:14, pro:0.4, carb:2.9, fib:0.9, sug:0.3, fat:0.3, sod:2 }]},
  { name:'Horseradish Root Fresh', cat:'Produce', peri:true, variants:[{ brand:'Generic', sz:5, su:'g', du:'g', cal:3, pro:0.1, carb:0.6, fib:0.2, sug:0.4, fat:0, sod:4 }]},
  // ─── Rice & Grains ───
  { name:'White Rice Long Grain Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:45, su:'g', du:'g', cal:160, pro:3, carb:35.7, fib:0.5, sug:0, fat:0.3, sod:0 }]},
  { name:'Brown Rice Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:45, su:'g', du:'g', cal:170, pro:3.7, carb:35.7, fib:2.1, sug:0, fat:1.5, sod:3 }]},
  { name:'Jasmine Rice Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:45, su:'g', du:'g', cal:160, pro:3, carb:36, fib:0, sug:0, fat:0, sod:0 }]},
  { name:'Basmati Rice Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:45, su:'g', du:'g', cal:160, pro:3, carb:36, fib:0.7, sug:0, fat:0.3, sod:0 }]},
  { name:'Wild Rice Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:40, su:'g', du:'g', cal:143, pro:5.9, carb:30, fib:2.5, sug:1.2, fat:0.5, sod:3 }]},
  { name:'Quinoa Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:42, su:'g', du:'g', cal:156, pro:6, carb:27.3, fib:2.8, sug:1.2, fat:2.6, sod:9 }]},
  { name:'Rolled Oats Old Fashioned', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:40, su:'g', du:'g', cal:150, pro:5, carb:27, fib:4, sug:1, fat:3, sod:0 }]},
  { name:'Steel Cut Oats', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:40, su:'g', du:'g', cal:150, pro:7, carb:27, fib:4, sug:0, fat:2.5, sod:0 }]},
  { name:'Cornmeal Yellow', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:30, su:'g', du:'g', cal:110, pro:2.5, carb:23.4, fib:1.4, sug:0.2, fat:1.1, sod:1 }]},
  { name:'Grits Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:35, su:'g', du:'g', cal:130, pro:3, carb:28, fib:1, sug:0, fat:0.5, sod:0 }]},
  { name:'Farro Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:45, su:'g', du:'g', cal:150, pro:6, carb:30, fib:3, sug:0, fat:1, sod:0 }]},
  { name:'Millet Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:48, su:'g', du:'g', cal:189, pro:5.5, carb:36.4, fib:4.2, sug:0, fat:2.1, sod:3 }]},
  { name:'Couscous Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:45, su:'g', du:'g', cal:157, pro:5.5, carb:32.5, fib:2.2, sug:0.2, fat:0.3, sod:5 }]},
  { name:'Bulgur Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:35, su:'g', du:'g', cal:120, pro:4.4, carb:26.7, fib:6, sug:0.1, fat:0.4, sod:5 }]},
  { name:'Polenta Dry', cat:'Rice & Grains', variants:[{ brand:'Generic', sz:35, su:'g', du:'g', cal:130, pro:3, carb:27, fib:1, sug:0, fat:1.5, sod:0 }]},
  // ─── Pasta & Noodles ───
  { name:'Pasta Spaghetti Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:200, pro:7, carb:40.7, fib:2.4, sug:0.7, fat:1, sod:0 }]},
  { name:'Pasta Penne Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:200, pro:7.3, carb:40, fib:2.5, sug:1, fat:1.3, sod:0 }]},
  { name:'Pasta Rotini Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:200, pro:7, carb:40.7, fib:2.4, sug:0.7, fat:1, sod:0 }]},
  { name:'Pasta Fettuccine Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:200, pro:7, carb:40, fib:2, sug:0.7, fat:1.5, sod:0 }]},
  { name:'Pasta Elbow Macaroni Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:200, pro:7, carb:41.3, fib:2, sug:1.3, fat:0.7, sod:0 }]},
  { name:'Pasta Bow Tie Farfalle Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:200, pro:7, carb:40, fib:2, sug:0.7, fat:1, sod:0 }]},
  { name:'Pasta Angel Hair Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:200, pro:7, carb:41, fib:2, sug:0.7, fat:1, sod:0 }]},
  { name:'Pasta Lasagna Noodles Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:196, pro:7.2, carb:38.2, fib:2.2, sug:1.3, fat:1, sod:0 }]},
  { name:'Pasta Rigatoni Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:200, pro:7, carb:40, fib:2, sug:0.7, fat:1, sod:0 }]},
  { name:'Pasta Whole Wheat Spaghetti Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:56, su:'g', du:'g', cal:180, pro:8, carb:39, fib:5, sug:1, fat:1.5, sod:0 }]},
  { name:'Egg Noodles Dry', cat:'Pasta & Noodles', variants:[{ brand:'Generic', sz:38, su:'g', du:'g', cal:145, pro:5, carb:26.7, fib:1.2, sug:0.7, fat:2, sod:10 }]},
  // ─── Dry Beans & Legumes ───
  { name:'Barley Pearled Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:50, su:'g', du:'g', cal:176, pro:4.9, carb:38.5, fib:7.8, sug:0.4, fat:0.6, sod:3 }]},
  { name:'Black Beans Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:159, pro:10.9, carb:28.6, fib:11.3, sug:0.6, fat:0.5, sod:1 }]},
  { name:'Kidney Beans Red Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:157, pro:10.7, carb:28.1, fib:11.3, sug:0.5, fat:0.5, sod:2 }]},
  { name:'Pinto Beans Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:160, pro:10.3, carb:29.6, fib:10.7, sug:0.4, fat:0.5, sod:1 }]},
  { name:'Navy Beans Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:164, pro:10.1, carb:29.4, fib:13.4, sug:0.6, fat:0.6, sod:0 }]},
  { name:'Chickpeas Garbanzo Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:179, pro:9.9, carb:29.9, fib:8.5, sug:5.3, fat:2.9, sod:6 }]},
  { name:'Lentils Green Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:48, su:'g', du:'g', cal:163, pro:12.7, carb:28.2, fib:11, sug:1.8, fat:0.5, sod:4 }]},
  { name:'Lentils Red Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:48, su:'g', du:'g', cal:163, pro:12.3, carb:28.1, fib:8, sug:1.8, fat:0.6, sod:4 }]},
  { name:'Split Peas Green Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:48, su:'g', du:'g', cal:165, pro:11.7, carb:29.3, fib:11.7, sug:4, fat:0.5, sod:4 }]},
  { name:'Great Northern Beans Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:160, pro:11, carb:28.7, fib:12.4, sug:0.5, fat:0.6, sod:0 }]},
  { name:'Cannellini Beans Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:160, pro:11, carb:28, fib:11, sug:0.5, fat:0.5, sod:0 }]},
  { name:'Lima Beans Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:160, pro:10.7, carb:28.3, fib:13.2, sug:2, fat:0.5, sod:3 }]},
  { name:'Edamame Dry Soybeans', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:193, pro:18.9, carb:11, fib:5.2, sug:4.5, fat:9.5, sod:2 }]},
  { name:'Black-Eyed Peas Dry', cat:'Dry Beans & Legumes', variants:[{ brand:'Generic', sz:46, su:'g', du:'g', cal:160, pro:10.7, carb:28, fib:11, sug:4, fat:0.5, sod:4 }]},
  // ─── Baking & Pantry ───
  { name:'Almonds Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:164, pro:6, carb:6.1, fib:3.5, sug:1.2, fat:14.2, sod:0 }]},
  { name:'Walnuts Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:185, pro:4.3, carb:3.9, fib:1.9, sug:0.7, fat:18.5, sod:1 }]},
  { name:'Pecans Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:196, pro:2.6, carb:3.9, fib:2.7, sug:1.1, fat:20.4, sod:0 }]},
  { name:'Cashews Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:157, pro:5.2, carb:8.6, fib:0.9, sug:1.7, fat:12.4, sod:3 }]},
  { name:'Pistachios Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:159, pro:5.7, carb:7.7, fib:3, sug:2.2, fat:12.9, sod:0 }]},
  { name:'Macadamia Nuts Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:204, pro:2.2, carb:3.9, fib:2.4, sug:1.3, fat:21.5, sod:1 }]},
  { name:'Hazelnuts Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:178, pro:4.2, carb:4.7, fib:2.8, sug:1.2, fat:17.2, sod:0 }]},
  { name:'Pine Nuts Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:191, pro:3.9, carb:3.7, fib:1, sug:1, fat:19.4, sod:1 }]},
  { name:'Brazil Nuts Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:187, pro:4.1, carb:3.3, fib:2.1, sug:0.7, fat:19, sod:1 }]},
  { name:'Peanuts Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:161, pro:7.3, carb:4.6, fib:2.4, sug:1.3, fat:14, sod:5 }]},
  { name:'Sunflower Seeds Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:166, pro:5.8, carb:5.7, fib:2.4, sug:0.8, fat:14.4, sod:1 }]},
  { name:'Pumpkin Seeds Raw', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:151, pro:8.5, carb:5, fib:1.1, sug:0.4, fat:13, sod:5 }]},
  { name:'Chia Seeds', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:138, pro:4.7, carb:11.9, fib:9.8, sug:0, fat:8.7, sod:5 }]},
  { name:'Flax Seeds', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:152, pro:5.2, carb:8.2, fib:7.6, sug:0.4, fat:12, sod:9 }]},
  { name:'Hemp Seeds', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:162, pro:9.5, carb:2.6, fib:1.2, sug:0.5, fat:14.6, sod:2 }]},
  { name:'Sesame Seeds', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:9, su:'g', du:'g', cal:52, pro:1.6, carb:2.1, fib:1.1, sug:0, fat:4.5, sod:1 }]},
  { name:'Poppy Seeds', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:9, su:'g', du:'g', cal:46, pro:1.6, carb:2.5, fib:1.2, sug:0.3, fat:3.8, sod:2 }]},
  { name:'Olive Oil Extra Virgin', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:119, pro:0, carb:0, fib:0, sug:0, fat:13.5, sod:0 }]},
  { name:'Canola Oil', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:124, pro:0, carb:0, fib:0, sug:0, fat:14, sod:0 }]},
  { name:'Coconut Oil', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:121, pro:0, carb:0, fib:0, sug:0, fat:13.5, sod:0 }]},
  { name:'Avocado Oil', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:124, pro:0, carb:0, fib:0, sug:0, fat:14, sod:0 }]},
  { name:'Sesame Oil', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:14, su:'g', du:'g', cal:120, pro:0, carb:0, fib:0, sug:0, fat:13.6, sod:0 }]},
  { name:'Maple Syrup', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:20, su:'ml', du:'ml', cal:52, pro:0, carb:13.4, fib:0, sug:12.1, fat:0.1, sod:2 }]},
  { name:'Agave Nectar', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:21, su:'g', du:'g', cal:64, pro:0.1, carb:16, fib:0.2, sug:14.9, fat:0, sod:1 }]},
  { name:'Molasses', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:20, su:'g', du:'g', cal:58, pro:0, carb:14.9, fib:0, sug:11.1, fat:0, sod:7 }]},
  { name:'Brown Rice Syrup', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:21, su:'g', du:'g', cal:75, pro:0, carb:18.5, fib:0, sug:0, fat:0, sod:0 }]},
  { name:'Corn Syrup Light', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:20, su:'ml', du:'ml', cal:57, pro:0, carb:15.6, fib:0, sug:6, fat:0, sod:14 }]},
  { name:'All Purpose Flour', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:30, su:'g', du:'g', cal:110, pro:3, carb:22.9, fib:0.8, sug:0.1, fat:0.3, sod:0 }]},
  { name:'Bread Flour', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:30, su:'g', du:'g', cal:110, pro:3.6, carb:22, fib:0.8, sug:0.1, fat:0.5, sod:0 }]},
  { name:'Cake Flour', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:30, su:'g', du:'g', cal:109, pro:2.5, carb:23.6, fib:0.6, sug:0.1, fat:0.2, sod:0 }]},
  { name:'Almond Flour', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:160, pro:6, carb:6, fib:3, sug:1, fat:14, sod:0 }]},
  { name:'Coconut Flour', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:28, su:'g', du:'g', cal:120, pro:4, carb:16, fib:10, sug:6, fat:4, sod:50 }]},
  { name:'Cornstarch', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:8, su:'g', du:'g', cal:30, pro:0, carb:7.2, fib:0.1, sug:0, fat:0, sod:1 }]},
  { name:'Baking Soda', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:1, su:'g', du:'g', cal:0, pro:0, carb:0, fib:0, sug:0, fat:0, sod:315 }]},
  { name:'Active Dry Yeast', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:7, su:'g', du:'g', cal:20, pro:3.1, carb:2.3, fib:1.5, sug:0, fat:0.4, sod:4 }]},
  { name:'Vanilla Extract Pure', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:4, su:'ml', du:'ml', cal:12, pro:0, carb:0.5, fib:0, sug:0.5, fat:0, sod:1 }]},
  { name:'Cocoa Powder Unsweetened', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:5, su:'g', du:'g', cal:12, pro:1.1, carb:3.1, fib:1.8, sug:0.1, fat:0.7, sod:1 }]},
  { name:'Gelatin Unflavored', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:7, su:'g', du:'g', cal:25, pro:6, carb:0, fib:0, sug:0, fat:0, sod:14 }]},
  { name:'Granulated White Sugar', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:4, su:'g', du:'g', cal:16, pro:0, carb:4.2, fib:0, sug:4.2, fat:0, sod:0 }]},
  { name:'Powdered Confectioners Sugar', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:8, su:'g', du:'g', cal:31, pro:0, carb:8, fib:0, sug:7.4, fat:0, sod:0 }]},
  { name:'Light Brown Sugar', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:4, su:'g', du:'g', cal:15, pro:0, carb:4, fib:0, sug:3.9, fat:0, sod:1 }]},
  { name:'Dark Brown Sugar', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:4, su:'g', du:'g', cal:15, pro:0, carb:4, fib:0, sug:3.8, fat:0, sod:1 }]},
  { name:'Coconut Sugar', cat:'Baking & Pantry', variants:[{ brand:'Generic', sz:4, su:'g', du:'g', cal:15, pro:0, carb:4, fib:0, sug:4, fat:0, sod:0 }]},
  // ─── Condiments & Sauces ───
  { name:'Apple Cider Vinegar', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:3, pro:0, carb:0.1, fib:0, sug:0.1, fat:0, sod:1 }]},
  { name:'White Vinegar Distilled', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:3, pro:0, carb:0.1, fib:0, sug:0, fat:0, sod:0 }]},
  { name:'Balsamic Vinegar', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:14, pro:0.1, carb:2.7, fib:0, sug:2.4, fat:0, sod:4 }]},
  { name:'Red Wine Vinegar', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:3, pro:0, carb:0.1, fib:0, sug:0.1, fat:0, sod:1 }]},
  { name:'Rice Vinegar', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:3, pro:0, carb:0.5, fib:0, sug:0.1, fat:0, sod:0 }]},
  { name:'Worcestershire Sauce', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:5, su:'ml', du:'ml', cal:4, pro:0.1, carb:1, fib:0, sug:0.5, fat:0, sod:65 }]},
  { name:'Fish Sauce', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:13, pro:1.9, carb:0.7, fib:0, sug:0.7, fat:0, sod:1413 }]},
  { name:'Oyster Sauce', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:15, su:'g', du:'g', cal:21, pro:0.4, carb:4.8, fib:0, sug:2.3, fat:0.1, sod:426 }]},
  { name:'Hoisin Sauce', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:16, su:'g', du:'g', cal:35, pro:0.5, carb:7.1, fib:0.4, sug:4.5, fat:0.5, sod:258 }]},
  { name:'Teriyaki Sauce', cat:'Condiments & Sauces', variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:17, pro:0.5, carb:3.8, fib:0.1, sug:3.2, fat:0.1, sod:339 }]},
  // ─── Soups & Broths ───
  { name:'Chicken Broth Low Sodium', cat:'Soups & Broths', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:15, pro:1, carb:1.3, fib:0, sug:0, fat:0.5, sod:72 }]},
  { name:'Chicken Broth Regular', cat:'Soups & Broths', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:15, pro:1, carb:1.3, fib:0, sug:0, fat:0.5, sod:570 }]},
  { name:'Beef Broth Low Sodium', cat:'Soups & Broths', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:20, pro:2.7, carb:0.7, fib:0, sug:0, fat:0.5, sod:72 }]},
  { name:'Beef Broth Regular', cat:'Soups & Broths', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:20, pro:2.7, carb:0.7, fib:0, sug:0, fat:0.5, sod:480 }]},
  { name:'Vegetable Broth', cat:'Soups & Broths', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:15, pro:0, carb:3, fib:0, sug:1, fat:0, sod:570 }]},
  { name:'Chicken Stock', cat:'Soups & Broths', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:38, pro:5, carb:0.5, fib:0, sug:0, fat:2, sod:343 }]},
  { name:'Beef Stock', cat:'Soups & Broths', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:38, pro:4.8, carb:0.9, fib:0, sug:0, fat:2, sod:343 }]},
  { name:'Fish Stock', cat:'Soups & Broths', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:40, pro:6, carb:0, fib:0, sug:0, fat:2, sod:363 }]},
  // ─── Beverages ───
  { name:'Orange Juice Fresh Squeezed', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:112, pro:1.7, carb:25.8, fib:0.5, sug:20.8, fat:0.5, sod:2 }]},
  { name:'Grape Juice Purple', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:152, pro:1.4, carb:37.4, fib:0.2, sug:36.2, fat:0.2, sod:13 }]},
  { name:'Grapefruit Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:96, pro:1.2, carb:22.7, fib:0.2, sug:21.1, fat:0.2, sod:2 }]},
  { name:'Lemon Juice Fresh', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:4, pro:0.1, carb:1.3, fib:0.1, sug:0.5, fat:0, sod:1 }]},
  { name:'Lime Juice Fresh', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:15, su:'ml', du:'ml', cal:4, pro:0.1, carb:1.4, fib:0.1, sug:0.3, fat:0, sod:1 }]},
  { name:'Pineapple Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:132, pro:0.9, carb:32.2, fib:0.5, sug:25, fat:0.2, sod:5 }]},
  { name:'Cranberry Juice Cocktail', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:137, pro:0.2, carb:34.2, fib:0.3, sug:32.7, fat:0.3, sod:5 }]},
  { name:'Tomato Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:41, pro:1.9, carb:10.3, fib:0.5, sug:8.7, fat:0.1, sod:654 }]},
  { name:'Carrot Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:94, pro:2.2, carb:21.9, fib:1.9, sug:9.2, fat:0.4, sod:68 }]},
  { name:'Pomegranate Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:134, pro:0.4, carb:32.7, fib:0.2, sug:31.5, fat:0.7, sod:22 }]},
  { name:'Watermelon Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:71, pro:1.4, carb:17.7, fib:0.5, sug:14.4, fat:0.4, sod:3 }]},
  { name:'Mango Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:128, pro:0.8, carb:33, fib:0.7, sug:28, fat:0.5, sod:10 }]},
  { name:'Cherry Juice Tart', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:130, pro:1, carb:32, fib:0, sug:24, fat:0, sod:20 }]},
  { name:'Beet Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:100, pro:3.4, carb:21.6, fib:0, sug:16.8, fat:0.4, sod:200 }]},
  { name:'Cucumber Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:32, pro:1.8, carb:5.8, fib:0.7, sug:3, fat:0.2, sod:14 }]},
  { name:'Celery Juice', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:42, pro:2, carb:7, fib:3.6, sug:5, fat:0.4, sod:215 }]},
  { name:'Green Juice Kale Spinach', cat:'Beverages', peri:true, variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:45, pro:3, carb:8, fib:2, sug:3, fat:0.5, sod:80 }]},
  { name:'Sparkling Water', cat:'Beverages', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:0, pro:0, carb:0, fib:0, sug:0, fat:0, sod:50 }]},
  { name:'Coconut Water', cat:'Beverages', variants:[{ brand:'Generic', sz:240, su:'ml', du:'ml', cal:46, pro:1.7, carb:8.9, fib:2.6, sug:6.3, fat:0.5, sod:252 }]},
]

export const STARTER_INGREDIENT_COUNT = DEFS.length

function build(d: IDef): Ingredient {
  const parentId = newId()
  const variants = d.variants.map(v => ({
    id: newId(),
    parentId,
    brand: v.brand,
    defaultUnit: v.du as IngredientUnit,
    servingSize: v.sz,
    servingUnit: v.su as IngredientUnit,
    macros: {
      calories: v.cal,
      protein:  v.pro,
      carbs:    v.carb,
      fiber:    v.fib,
      sugar:    v.sug,
      fat:      v.fat,
      sodium:   v.sod,
      ...(v.sf !== undefined ? { saturatedFat: v.sf } : {}),
    },
    ...(v.fdc ? { usdaFdcId: v.fdc } : {}),
  }))
  return {
    id: parentId,
    name: d.name,
    category: d.cat,
    perishable: d.peri ?? false,
    frozen: false,
    alwaysOnHand: false,
    archived: false,
    defaultVariantId: variants[0].id,
    createdAt: now(),
    updatedAt: now(),
    variants,
  }
}

export async function seedStarterLibrary(): Promise<number> {
  const existing = await getAllIngredients(true)
  const existingNames = new Set(existing.map(i => i.name.toLowerCase()))
  let count = 0
  for (const def of DEFS) {
    if (!existingNames.has(def.name.toLowerCase())) {
      await saveIngredient(build(def))
      count++
    }
  }
  return count
}

export async function migrateStarterLibrary(): Promise<number> {
  const existing = await getAllIngredients(true)
  const legacySet = new Set(LEGACY_FLAT_NAMES.map(n => n.toLowerCase()))
  const toDelete = existing.filter(ing =>
    legacySet.has(ing.name.toLowerCase()) &&
    ing.variants.length === 1 &&
    ing.variants[0].brand.toLowerCase() === 'generic'
  )
  for (const ing of toDelete) {
    await deleteIngredient(ing.id)
  }
  return seedStarterLibrary()
}
